config/routes.rb
Rails.application.routes.draw do
 get 'accounts/vat_lookup', to: 'accounts#vat_lookup', defaults: { format: :json }
 resources :accounts
 root 'accounts#index'
end

app/models/account.rb
class Account < ApplicationRecord
  validates :name, presence: true
  validates :vat, uniqueness: true, presence: true, format: { with: /\AEL\d{9}\z/, message: "must be in the format EL and 9 digits" }
  validates :city, presence: true
  validates :zipcode, presence: true
  validates :address, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/accounts_controller.rb
require 'httparty'

class AccountsController < ApplicationController
  include HTTParty
  before_action :set_account, only: %i[show edit update destroy]
  
  def index
    @accounts = Account.all
  end
  
  def show
   @account= Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
        
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
        
      end
    end
  end

  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def vat_lookup
    vat = params[:vat]
    country_code = vat[0, 2]
    vat_number = vat[2..-1]

    response = HTTParty.post(
      'https://ec.europa.eu/taxation_customs/vies/rest-api/check-vat-number',
      body: {
        countryCode: country_code,
        vatNumber: vat_number
      }.to_json,
      headers: { 'Content-Type' => 'application/json' }
    )

    if response.success?    
        
      parsed_response = JSON.parse(response.body)

      if parsed_response['valid']          
        # Use regular expressions to extract address, zip code, and city
        address_match = parsed_response['address'].match(/^(.*?)\s+(\d{5})\s+-\s+(.*)$/)
        if address_match
          address = address_match[1].strip
          zip_code = address_match[2].strip
          city = address_match[3].strip

          result = {
            name: parsed_response['name'],
            address: address,
            zip_code: zip_code,
            city: city
          }

          render json: result
       else         
         render json: { error: 'Failed to parse address' }, status: :unprocessable_entity
       end

      else
        render json: { error: 'Invalid VAT number'}, status: :unprocessable_entity
      end
    else
      render json: { error: 'Failed to check VAT number' }, status: :bad_request
    end
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:name, :vat, :city, :zipcode, :address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
<p>
<strong>Name:</strong>
<%= account.name %>
</p>

<p>
<strong>VAT:</strong>
<%= account.vat %>
</p>

</div>

app/views/accounts/_form.html.erb
<%= form_with(model: @account, data: {turbo: false}) do |form| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
        <% @account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: 'account_name' %>
  </div>

  <div class="field">
    <%= form.label :vat %>
    <%= form.text_field :vat, id: 'account_vat', value: 'EL' %>
    <button type="button" id="vat_lookup_button">🔎</button>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: 'account_city' %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, id: 'account_zipcode' %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: 'account_address' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>

<div id="accounts">
  <% @accounts.each do |account| %>
    <%= render account %>
    <p>
      <%= link_to "Show this account", account %>
    </p>
  <% end %>
</div>

<%= link_to "New account", new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Account Details</h1>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Vat:</strong>
  <%= @account.vat %>
</p>

<p>
  <strong>City:</strong>
  <%= @account.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @account.zipcode %>
</p>

<p>
  <strong>Address:</strong>
  <%= @account.address %>
</p>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Delete this account", @account, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>    
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>